const data = {
  products: [
    {
      name: "Хрест накупольний",
      slug: "cross1",
      category: "Cross",
      image: "/images/products/cross1.jpg",
      price: 10000,
      rating: 4.5,
      numReviews: 2,
      countInStock: 1,
      description:
        "Хрест церковний накупольний, нержавіюча сталь, покритий в золото, 0.75 м",
      isFeatured: true,
    },
    {
      name: "Хрест накупольний",
      slug: "cross2",
      category: "Cross",
      image: "/images/products/cross2.jpg",
      price: 10000,
      rating: 4.5,
      numReviews: 2,
      countInStock: 1,
      description:
        "Хрест церковний накупольний, нержавіюча сталь, покритий в золото, 0.75 м",
      isFeatured: true,
    },
    {
      name: "Хрест накупольний",
      slug: "cross3",
      category: "Cross",
      image: "/images/products/cross3.jpg",
      price: 10000,
      rating: 4.5,
      numReviews: 2,
      countInStock: 1,
      description:
        "Хрест церковний накупольний, нержавіюча сталь, покритий в золото, 0.75 м",
      isFeatured: true,
    },
    {
      name: "Хрест накупольний",
      slug: "cross4",
      category: "Cross",
      image: "/images/products/cross4.jpg",
      price: 10000,
      rating: 4.5,
      numReviews: 2,
      countInStock: 1,
      description:
        "Хрест церковний накупольний, нержавіюча сталь, покритий в золото, 0.75 м",
      isFeatured: true,
    },
    {
      name: "Хрест накупольний",
      slug: "cross5",
      category: "Cross",
      image: "/images/products/cross5.jpg",
      price: 10000,
      rating: 4.5,
      numReviews: 2,
      countInStock: 1,
      description:
        "Хрест церковний накупольний, нержавіюча сталь, покритий в золото, 0.75 м",
      isFeatured: true,
    },
    {
      name: "Хрест накупольний",
      slug: "cross6",
      category: "Cross",
      image: "/images/products/cross6.jpg",
      price: 18000,
      rating: 4.5,
      numReviews: 2,
      countInStock: 1,
      description:
        "Хрест церковний накупольний, нержавіюча сталь, покритий в золото, 0.75 м, LED",
      isFeatured: true,
    },
    {
      name: "Купол церковний з нержавіючої сталі, розмір 1 м",
      slug: "domes-1",
      category: "Domes",
      image: "/images/products/dome1.jpg",
      price: 22000,
      rating: 4.7,
      numReviews: 2,
      countInStock: 6,
      description:
        "Країна виробництва: Україна, вид: грушоподібні (луковіцевідні), матеріал: нержавіюча сталь, поверхня гладка, каркас: метал; в наявності золотий та синій кольори.",
      isFeatured: true,
    },
    {
      name: "Купол церковний з нержавіючої сталі, розмір 1,10 м",
      slug: "domes-2",
      category: "Domes",
      image: "/images/products/dome2.jpg",
      price: 26000,
      rating: 4.9,
      numReviews: 4,
      countInStock: 1,
      description:
        "Країна виробництва: Україна, вид: грушоподібні (луковіцевідні), матеріал: нержавіюча сталь, поверхня гладка, каркас: металю. Колір золотий.",
      isFeatured: true,
    },
    {
      name: "Купол церковний з нержавіючої сталі, розмір 1,10 м",
      slug: "domes-3",
      category: "Domes",
      image: "/images/products/dome3.jpg",
      price: 26000,
      rating: 4.9,
      numReviews: 4,
      countInStock: 1,
      description:
        "Країна виробництва: Україна, вид: грушоподібні (луковіцевідні), матеріал: нержавіюча сталь, поверхня гладка, каркас: металю. Колір зелено-золотий.",
      isFeatured: true,
    },
    {
      name: "Купол церковний з нержавіючої сталі, розмір 1,10 м",
      slug: "domes-4",
      category: "Domes",
      image: "/images/products/dome4.jpg",
      price: 24000,
      rating: 4.9,
      numReviews: 4,
      countInStock: 1,
      description:
        "Країна виробництва: Україна, вид: грушоподібні (луковіцевідні), матеріал: нержавіюча сталь, поверхня гладка, каркас: металю. Колір зелено-золотий.",
      isFeatured: true,
    },
    {
      name: "Купол церковний з нержавіючої сталі, розмір 2,50 м",
      slug: "domes-5",
      category: "Domes",
      image: "/images/products/dome5.jpg",
      price: 40000,
      rating: 5,
      numReviews: 6,
      countInStock: 1,
      description:
        "Країна виробництва: Україна, вид: грушоподібні (луковіцевідні), матеріал: нержавіюча сталь, поверхня гладка, каркас: металю. Колір золотий.",
      isFeatured: true,
    },
    {
      name: "Купол церковний з нержавіючої сталі, розмір 0,9 м",
      slug: "domes-6",
      category: "Domes",
      image: "/images/products/dome6.jpg",
      price: 20000,
      rating: 4.5,
      numReviews: 1,
      countInStock: 1,
      description:
        "Країна виробництва: Україна, вид: грушоподібні (луковіцевідні), матеріал: нержавіюча сталь, поверхня гладка, каркас: металю. Колір золотий.",
      isFeatured: true,
    },
    {
      name: "Аркуш ",
      slug: "sheets-1",
      category: "Sheets",
      image: "/images/products/sheets1.jpg",
      price: 4500,
      rating: 5,
      numReviews: 1,
      countInStock: 15,
      description:
        "Країна виробництва: Україна, розмір 1000*2000*0.4мм, матеріал: високоякісна технічна магнітна сталь, відповідно до стандарту AISI 430. Кольори: золотий, мідний, зелений та небесно-синій",
      isFeatured: true,
    },
    {
      name: "Декоративні елементи",
      slug: "decor-1",
      category: "Decor",
      image: "/images/products/decor1.jpg",
      price: 4500,
      rating: 5,
      numReviews: 1,
      countInStock: 2,
      description:
        "Країна виробництва: Україна, матеріал: високоякісна технічна магнітна сталь. Кольори: золотий, мідний, зелений та небесно-синій",
      isFeatured: true,
    },
    {
      name: "Підставка під квіти",
      slug: "decor-2",
      category: "Decor",
      image: "/images/products/decor2.jpg",
      price: 7000,
      rating: 4.9,
      numReviews: 1,
      countInStock: 1,
      description:
        "Країна виробництва: Україна, тип: підставки, розташування: підлогові, матеріал: нержавіюча сталь, висота: 900 мм, колір: золотий",
      isFeatured: true,
    },
    {
      name: "Куля декоративна",
      slug: "decor-3",
      category: "Decor",
      image: "/images/products/decor3.jpg",
      price: 4000,
      rating: 4.9,
      numReviews: 1,
      countInStock: 1,
      description:
        "Країна виробництва: Україна, діаметр: 300мм, вид: ковані елементи, спосіб виробництва: штампування, матеріал: нержавіюча сталь марки AISI304, колір золотий.",
      isFeatured: true,
    },
    {
      name: "Декоративні елементи",
      slug: "decor-4",
      category: "Decor",
      image: "/images/products/decor4.jpg",
      price: 4000,
      rating: 5,
      numReviews: 1,
      countInStock: 2,
      description:
        "Країна виробництва: Україна, матеріал: високоякісна технічна магнітна сталь. Кольори: золотий, мідний, зелений та небесно-синій",
      isFeatured: true,
    },
    {
      name: "Куля декоративна",
      slug: "decor-5",
      category: "Decor",
      image: "/images/products/decor5.jpg",
      price: 3700,
      rating: 4.9,
      numReviews: 1,
      countInStock: 1,
      description:
        "Країна виробництва: Україна, діаметр: 300мм, вид: ковані елементи, спосіб виробництва: штампування, матеріал: нержавіюча сталь марки AISI304, колір срібний.",
      isFeatured: true,
    },
    {
      name: "Декоративні елементи",
      slug: "decor-6",
      category: "Decor",
      image: "/images/products/decor6.jpg",
      price: 7000,
      rating: 5,
      numReviews: 1,
      countInStock: 2,
      description:
        "Країна виробництва: Україна, матеріал: високоякісна технічна магнітна сталь. Колір: золотий",
      isFeatured: true,
    },
  ],
};

export default data;
