import InfoPanel from '@/components/InfoPanel/InfoPanel';
import TheHeader from '@/components/TheHeader/TheHeader';
import TheFooter from '@/components/TheFooter/TheFooter';

import "./globals.css";

import { Roboto } from "next/font/google";
const roboto = Roboto({
  subsets: ["cyrillic"],
  variable: "--font-roboto",
  weight: ["400", "500", "700", "900"],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <InfoPanel />
        <TheHeader />
          <main className=''>{children}</main>
        <TheFooter />
      </body>            
    </html>
  )
}
