import TheHeader from '@/components/TheHeader/TheHeader';
import TheFooter from '@/components/TheFooter/TheFooter';

import styles from '@/app/layout.module.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.container}>
        <TheHeader />
          <main>{children}</main>
        <TheFooter />
      </body>            
    </html>
  )
}
